### ISSUE TITLE
who you trying to rat?

### ISSUE THREAD

**Issue by CRiQ01** [VinieClara/FN-Manfiestes#1]
Hi

**Comment by VinieClara** [comment]
For you to know this is not a rat and im the developer and provider of https://luckycharm.network not the person who tried to infect you.

**Comment by CRiQ01** [comment]
Whoever you are, there is a lib that is used by keyauth that has been added into multiple sources around github. Whenever keyauth is initiated, a suspicious program is created into SYSWOW64 from bytes requesting for this link on your github. Grabbing the website you added in this repo and making requests, sending and receiving small packages from your website that you added here. I guess there isn't a coincidence tho

**Comment by CRiQ01** [comment]
Are you really the owner? Or Emosha Emre is? :)
